paths:
  /cosmos:
    get:
      tags:
        - 'cosmos'
      summary: 'View the Cosmos network and RPC URL that gateway is configured to use'
      description: 'The user can change this by editing src/chains/cosmos/cosmos.config.ts'
      operationId: 'root'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Cosmos config'
          schema:
            $ref: '#/definitions/CosmosConfigResponse'

  /cosmos/balances:
    post:
      tags:
        - 'cosmos'
      summary: 'Get the balances of a Cosmos wallet'
      operationId: 'balances'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/CosmosBalancesRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/SolanaBalancesResponse'

  /cosmos/token:
    get:
      tags:
        - 'cosmos'
      summary: 'Request token information and balance of requested token symbol'
      operationId: 'token'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/SolanaTokenRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/SolanaTokenResponse'
    post:
      tags:
        - 'cosmos'
      summary: 'Get or create an associated token account for given token symbol. NOTE: This request costs 0.035 SOL, if no associated token account for given wallet address existed so far'
      operationId: 'token'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/SolanaTokenRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/SolanaTokenResponse'

  /cosmos/poll:
    post:
      tags:
        - 'cosmos'
      summary: 'Poll the status of a Cosmos transaction'
      operationId: 'poll'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/SolanaPollRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/SolanaPollResponse'
